# Generated by Django 5.0.2 on 2024-03-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
