# Generated by Django 5.0.2 on 2024-03-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
